version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: meeting_intel
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  meeting-intelligence:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres/meeting_intel
    volumes:
      - ./config:/app/config
    depends_on:
      - postgres

volumes:
  postgres_data: